learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
""""learning_logsのurlパターンの定義"""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # ホームページ
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
]

learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """モデルの文字列表現を返す"""
        return self.text

class Entry(models.Model):
    """トピックについて学んだこと"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """モデルの文字列表現を返す"""
        return f"{self.text[:25]}..."

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect

from .models import Topic
from .forms import TopicForm, EntryForm

# Create your views here.

def index(request):
    """学習ノートのホームページ"""
    return render(request, 'learning_logs/index.html')

def topics(request):
    """全てのトピックを表示する"""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    """１つのトピックとそれについての全ての記事を表示"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by(('-date_added'))
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

def new_topic(request):
    """新規トピックを追加する"""
    if request.method != 'POST':
        #　データが送信されていないのでからのフォームを生成する
        form = TopicForm()
    else:
        #　POSTでデータが送信されたのでこれを処理する
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')

    # 空のまたは無効のフォームを表示する
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

def new_entry(request, topic_id):
    """特定のトピックに新規記事を追加する"""
    topic = Topic.objects.get(id=topic_id)

    if(request.method != 'POST'):
        # データは送信されていないのでからのフォームを生成する
        form = EntryForm()
    else:
        #POSTでデータが送信されたのでこれを処理する
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    # 空または無効のフォームを表示する
    context = {'topic': topic, 'form': form}

    return render(request, 'learning_logs/new_entry.html', context)

learning_logs/templates/learning_logs/base.html
<h1>
    <a href="{% url 'learning_logs:index'%}">学習記録帳</a> -
    <a href="{% url 'learning_logs:topics' %}">トピック一覧</a>
</h1>

{%  block content %}{% endblock content %}

learning_logs/templates/learning_logs/index.html
{%  extends "learning_logs/base.html" %}

{% block content %}
<p>学習記録帳は自分が学んだことのログを残すことができます</p>

{%  endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

    <p>新しい学習内容の追加</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>学習内容の追加</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p>新規トピックを追加：</p>

    <form action = "{% url 'learning_logs:new_topic' %}" method='post'>
        {% csrf_token %}
        {{form.as_p}}
        <button name = "submit"> トピックを追加する</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p>トピック： {{ topic }}</p>

<p>学習内容:</p>
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">新しい学習内容を追加</a>
    </p>
<ul>
    {%for entry in entries %}
        <li>
        <p>{{ entry.date_added|date:'Y年m月d日H;i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
        </li>
    {% empty %}
        <li>このトピックにはまだ学習内容がありません。</li>
    {% endfor %}
</ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p>トピック一覧</p>

    <ul>
        {% for topic in topics %}
            <li>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
            </li>
        {% empty %}
            <li>トピックはまだ作成されていません。</li>
        {% endfor %}
    </ul>

    <a href="{% url 'learning_logs:new_topic' %}">新規トピックの追加</a>

{% endblock content %}